"""Kubernetes API wrapper for the GPU reservation controller.

All blocking kubernetes-client calls run in a thread-pool executor so they
never stall the asyncio event loop.

Public surface
--------------
init_k8s(kubeconfig_path, strict_tls_verify)  — load credentials once at startup
get_pod_gpu_count(pod)                       — sum nvidia.com/gpu requests
get_pod_booking_reference(pod)               — read galends/booking-reference annotation
get_pod_usage_group(pod)                     — read galends/usage-group annotation (JIT lease group)
get_pod_annotation_problems(pod, ...)        — job-input annotations the controller will ignore, and why
get_pod_galends_annotations(pod)             — every galends/* annotation, bounded (JIT admission ask)
parse_booking_reference(ref)                 — reservation id from a booking-reference
pod_has_toleration(pod, ...)                 — check for a specific toleration
is_gpu_gated_pending(pod, taint_key)         — guard 1: is Pending fixable by a lease?
read_pod(name, namespace)                    — fetch current pod object
snapshot_tolerated_pods(tol_key)             — one LIST → occupancy + claims + guard 3
get_node_forced_gpu_capacity(node)           — read galends/force-node-capacity annotation
snapshot_node_gpu_inventory(taint_key)       — one LIST → allocatable GPUs per class, per node
snapshot_node_gpu_capacity(taint_key)        — per-class collapse of the inventory (preemption planning)
apply_toleration(...)                        — PATCH a pod to add toleration + booking annotation
PodWatcher                                   — async-generator based pod event stream
acquire_singleton_lease / renew_singleton_lease — coordination Lease duplicate-instance guard
"""

from __future__ import annotations

import asyncio
import functools
import logging
import re
import ssl
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone, tzinfo
from typing import AsyncIterator, Callable, NamedTuple, Optional, TypeVar

from kubernetes import client as k8s_client, config as k8s_config, watch
from kubernetes.client.rest import ApiException
from urllib3.util.ssl_ import create_urllib3_context

from .log_fields import kv

log = logging.getLogger(__name__)

# Initialised once by init_k8s(); used by all functions in this module.
_core_v1: Optional[k8s_client.CoreV1Api] = None
_coordination_v1: Optional[k8s_client.CoordinationV1Api] = None


# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------


def init_k8s(
    kubeconfig_path: Optional[str], *, strict_tls_verify: bool = True
) -> None:
    """Load Kubernetes credentials and create the API clients.

    *strict_tls_verify* is ``K8S_TLS_STRICT_VERIFY``; ``False`` relaxes the
    OpenSSL strict X.509 checks on the API server connection — see
    ``_relax_strict_tls_verify`` for what that does and does not give up.
    """
    global _core_v1, _coordination_v1
    if kubeconfig_path:
        k8s_config.load_kube_config(config_file=kubeconfig_path)
        log.info("%s", kv(event="k8s.auth", mode="kubeconfig", path=kubeconfig_path))
    else:
        k8s_config.load_incluster_config()
        log.info("%s", kv(event="k8s.auth", mode="in_cluster"))
    _core_v1 = k8s_client.CoreV1Api()
    _coordination_v1 = k8s_client.CoordinationV1Api()
    if not strict_tls_verify:
        _relax_strict_tls_verify(_core_v1.api_client, _coordination_v1.api_client)
        log.warning("%s", kv(
            event="k8s.tls_relaxed",
            name="K8S_TLS_STRICT_VERIFY",
            detail=(
                "strict X.509 checks disabled on the Kubernetes API connection; "
                "chain, validity and hostname are still verified"
            ),
        ))


def _relax_strict_tls_verify(*api_clients) -> None:
    """Clear ``VERIFY_X509_STRICT`` on each API client's connection pool.

    Python 3.13's ``ssl.create_default_context()`` turns on
    ``VERIFY_X509_STRICT``, and urllib3 2.x mirrors that in the context it
    builds for every HTTPS pool.  Under that flag OpenSSL requires an Authority
    Key Identifier extension on the certificates it chains through, which a
    cluster PKI generated by older tooling may not carry.  The connection then
    fails with ``CERTIFICATE_VERIFY_FAILED ... Missing Authority Key
    Identifier`` even though the service account's ``ca.crt`` is mounted and
    correct — the same image on Python 3.12 connected fine.  Regenerating the
    apiserver certificate with an AKID is the real fix; this is the escape
    hatch for a cluster where that is not immediately possible.

    It is deliberately **not** ``verify_ssl: false``.  The chain is still built
    and verified against the mounted CA, validity dates still apply, and the
    hostname is still matched; only the AKID-presence requirement is dropped.
    The context is otherwise exactly the one urllib3 would have built for this
    client, so nothing else about the TLS posture changes, and the CA file is
    still loaded into it by ``ssl_wrap_socket`` at connect time.

    Every API client owns its own ``RESTClientObject``, hence its own pool
    manager, so each is handed its own context.  Pool objects are built lazily
    from ``connection_pool_kw`` on first use, which is why this runs at startup
    before any request: a pool that already existed would keep the strict
    context it was created with.
    """
    for api_client in api_clients:
        pool_kw = api_client.rest_client.pool_manager.connection_pool_kw
        context = create_urllib3_context(cert_reqs=pool_kw.get("cert_reqs"))
        context.verify_flags &= ~ssl.VERIFY_X509_STRICT
        pool_kw["ssl_context"] = context


# ---------------------------------------------------------------------------
# Pure helpers (synchronous, no I/O)
# ---------------------------------------------------------------------------


# Phases from which a pod never returns to Running — its GPU slot is free and
# it should be released from occupancy.  Defined once here (next to
# get_pod_phase) so the watch loop, the reserved path, and the on-demand path
# all agree on what "terminal" means (CODE-REVIEW D1c).  The on-demand *drop*
# additionally treats "Unknown" as gone-for-placement (TERMINAL_PHASES +
# ("Unknown",)); that is a placement decision, not an occupancy release.
TERMINAL_PHASES = ("Succeeded", "Failed")


def get_pod_phase(pod) -> str:
    """Return the pod's phase string (e.g. "Pending", "Running", "Succeeded", "Failed").

    Returns an empty string if the phase is unavailable.
    """
    return (pod.status.phase if pod.status else None) or ""


def is_terminal_phase(pod) -> bool:
    """Return True if *pod* is in a terminal phase (Succeeded/Failed)."""
    return get_pod_phase(pod) in TERMINAL_PHASES


def get_pod_creation_timestamp(pod) -> Optional[datetime]:
    """Return the pod's ``metadata.creationTimestamp``, or ``None`` if unset."""
    return pod.metadata.creation_timestamp


def get_unschedulable_message(pod) -> str:
    """Return the ``PodScheduled`` condition message, truncated to 120 chars.

    Empty string when there is no such condition.  Owning the pod-object dig
    here keeps ``main.py`` out of ``pod.status.conditions`` internals
    (CODE-REVIEW D10).
    """
    conditions = (pod.status.conditions or []) if pod.status else []
    scheduled = next((c for c in conditions if c.type == "PodScheduled"), None)
    if scheduled is None:
        return ""
    return (scheduled.message or "")[:120]


# The galends/* job-input annotations a pod author writes and this module reads
# (see docs/POD-ANNOTATIONS.md §3).
MIN_RUNTIME_ANNOTATION = "galends/minimum-runtime-seconds"
RUNTIME_GUARANTEE_ANNOTATION = "galends/runtime-guarantee"
USAGE_GROUP_ANNOTATION = "galends/usage-group"

# Recognised values of the galends/runtime-guarantee pod annotation. A set
# rather than a bare literal so an added posture (say a future "soft") is one
# entry plus its handling, not a new parse path.
RUNTIME_GUARANTEE_VALUES = frozenset({"none"})


class AnnotationProblem(NamedTuple):
    """One job-input annotation on a pod that the controller had to ignore.

    ``reason`` is the same vocabulary ``pod.annotation_invalid`` logs --
    ``not_an_integer``, ``not_positive``, ``unrecognised_value`` -- plus
    ``not_enabled``: a well-formed request for something this deployment does
    not offer (``galends/runtime-guarantee`` while best-effort admission is
    off).  ``value`` is the annotation's value exactly as written.
    """

    annotation: str
    value: str
    reason: str


def _parse_min_runtime(raw) -> tuple[Optional[int], Optional[str]]:
    """``(seconds, None)`` for a positive integer, ``(None, reason)`` for any
    other value, ``(None, None)`` when the annotation is absent.

    The single definition of what ``galends/minimum-runtime-seconds`` accepts,
    shared by the logging getter and :func:`get_pod_annotation_problems` so the
    log line and the pod's Event can never disagree about a value.
    """
    if raw is None:
        return None, None
    try:
        value = int(raw)
    except (ValueError, TypeError):
        return None, "not_an_integer"
    if value <= 0:
        return None, "not_positive"
    return value, None


def _parse_runtime_guarantee(raw) -> tuple[Optional[str], Optional[str]]:
    """``(value, None)`` for a recognised value, ``(None, "unrecognised_value")``
    for any other, ``(None, None)`` when the annotation is absent.

    Case and surrounding whitespace are forgiven.  Shared like
    :func:`_parse_min_runtime`, for the same reason.
    """
    if raw is None:
        return None, None
    value = raw.strip().lower() if isinstance(raw, str) else raw
    if value in RUNTIME_GUARANTEE_VALUES:
        return value, None
    return None, "unrecognised_value"


def get_pod_min_runtime_seconds(pod) -> Optional[int]:
    """Read the ``galends/minimum-runtime-seconds`` annotation from *pod*.

    Returns the integer value if the annotation is present and parseable as a
    positive integer, or ``None`` otherwise.

    A non-positive value is rejected like junk, and says so: the floor is what
    makes the annotation mean "run me for at least this long", and ``0`` cannot
    express that.  It reads as a request for no runtime guarantee, which is a
    real thing to want and has its own annotation
    (``galends/runtime-guarantee: none`` -- see
    :func:`get_pod_runtime_guarantee_request`), so the warning names it.  Before
    that annotation existed a ``0`` here silently disqualified the pod from JIT
    admission with nothing logged at any level, and it sat Pending forever.
    """
    annotations: dict = pod.metadata.annotations or {}
    raw = annotations.get(MIN_RUNTIME_ANNOTATION)
    value, reason = _parse_min_runtime(raw)
    if reason == "not_an_integer":
        log.warning("%s", kv(
            event="pod.annotation_invalid",
            ns=pod.metadata.namespace, pod=pod.metadata.name,
            annotation=MIN_RUNTIME_ANNOTATION, value=raw,
            reason="not_an_integer",
        ))
    elif reason == "not_positive":
        log.warning("%s", kv(
            event="pod.annotation_invalid",
            ns=pod.metadata.namespace, pod=pod.metadata.name,
            annotation=MIN_RUNTIME_ANNOTATION, value=raw,
            reason="not_positive",
            detail="use galends/runtime-guarantee=none to request no guarantee",
        ))
    return value


def get_pod_runtime_guarantee_request(pod) -> Optional[str]:
    """Read the ``galends/runtime-guarantee`` annotation from *pod*.

    The pod's own statement of what runtime protection it wants.  Exactly one
    value is defined: ``"none"`` -- admit me with no runtime guarantee at all,
    on idle capacity I will give back the moment anything else needs it.  Such a
    pod is admitted under a zero-length, zero-SU ``kind="best_effort"``
    reservation, so it is preemptible from its first tick.

    Returns the recognised value, or ``None`` when the annotation is absent or
    unrecognised.  An unrecognised value logs ``pod.annotation_invalid`` and
    falls through to ordinary handling rather than failing the pod: the same
    tolerant-parse-and-say-so posture ``config.py`` takes, for the same reason
    (an operator who set something and saw no effect can find out why).

    Deliberately separate from ``galends/minimum-runtime-seconds``, which sizes
    a *lease*.  The two compose -- a pod may name a runtime and still waive the
    guarantee -- and keeping the posture out of the duration means neither has
    to carry a sentinel value for the other's sake.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    raw = annotations.get(RUNTIME_GUARANTEE_ANNOTATION)
    value, reason = _parse_runtime_guarantee(raw)
    if reason is not None:
        log.warning("%s", kv(
            event="pod.annotation_invalid",
            ns=pod.metadata.namespace, pod=pod.metadata.name,
            annotation=RUNTIME_GUARANTEE_ANNOTATION, value=raw,
            reason=reason,
            detail="expected: " + ", ".join(sorted(RUNTIME_GUARANTEE_VALUES)),
        ))
    return value


def get_pod_annotation_problems(
    pod, *, best_effort_enabled: bool
) -> list[AnnotationProblem]:
    """Every job-input annotation on *pod* that the controller will ignore.

    The pod-facing counterpart of the ``pod.annotation_invalid`` log line: the
    same verdicts (the parse is shared), gathered so the pod's owner can be told
    in an Event rather than only an operator in the log.  Pure -- no logging;
    the getters above already log each rejection.

    ``galends/runtime-guarantee`` is reported as ``not_enabled`` whatever it
    says while *best_effort_enabled* is off, because then no value of it is
    honoured, and telling someone their value is merely misspelled would send
    them round a second time.  ``galends/usage-group`` is never reported: it is
    free text the app judges (an unknown group is the app's 404 to relay).
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    problems: list[AnnotationProblem] = []

    raw = annotations.get(MIN_RUNTIME_ANNOTATION)
    _value, reason = _parse_min_runtime(raw)
    if reason is not None:
        problems.append(AnnotationProblem(MIN_RUNTIME_ANNOTATION, str(raw), reason))

    raw = annotations.get(RUNTIME_GUARANTEE_ANNOTATION)
    if raw is not None:
        _value, reason = _parse_runtime_guarantee(raw)
        if not best_effort_enabled:
            reason = "not_enabled"
        if reason is not None:
            problems.append(
                AnnotationProblem(RUNTIME_GUARANTEE_ANNOTATION, str(raw), reason)
            )
    return problems


def get_pod_usage_group(pod) -> Optional[str]:
    """Read the ``galends/usage-group`` annotation from *pod*.

    Names the usage group a JIT on-demand lease should be created under —
    ``group_name`` is a required natural key on the app's lease-create endpoint
    (RESERVATION-API.md §"Creating on-demand reservations": the user supplies
    their group via this pod annotation).  Only consulted when
    ``REQUIRED_GROUP_LABEL`` is disabled; when that feature is on, the group
    label is both the match axis and the group source.  Returns ``None`` when
    the annotation is absent or empty.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    return annotations.get(USAGE_GROUP_ANNOTATION) or None


def get_pod_gpu_count(pod) -> int:
    """Sum nvidia.com/gpu resource requests across all containers in *pod*."""
    total = 0
    for container in pod.spec.containers or []:
        requests = (
            (container.resources.requests or {}) if container.resources else {}
        )
        try:
            total += int(requests.get("nvidia.com/gpu", 0))
        except (ValueError, TypeError):
            pass
    return total


def get_pod_booking_reference(pod) -> Optional[str]:
    """Return the ``galends/booking-reference`` annotation value, or ``None``."""
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    return annotations.get("galends/booking-reference")


# The annotation namespace this system owns.  Every key the controller writes,
# and every key it reads off a pod, carries it -- so the prefix is also what marks
# a pod annotation as *about* the reservation system, and therefore worth
# forwarding to the app with a JIT admission ask (see
# ``get_pod_galends_annotations``).  Matched with the trailing slash, which is
# what keeps an unrelated ``galends.example.com/...`` key out.
GALENDS_PREFIX = "galends/"

# Bounds applied when forwarding those annotations off-cluster.  Their values are
# whatever the pod's creator wrote, and Kubernetes caps *all* annotations on an
# object at 256 KiB -- which an admission batch would otherwise carry per
# candidate, every 2-5 minutes, for as long as the pod stays Pending.  Capping
# here rather than in the app is deliberate: the app's schema is lenient on
# purpose, because a rejected candidate 422s the whole batch (RESERVATION-API.md
# "POST /api/reservations/ondemand-admission"), so the controller must never send
# something the far end would refuse.
GALENDS_ANNOTATION_MAX_KEYS = 32
GALENDS_ANNOTATION_MAX_VALUE = 1024


def get_pod_galends_annotations(pod) -> dict[str, str]:
    """Return the pod's ``galends/``-prefixed annotations, bounded for the wire.

    Unlike the single-key readers above this makes no judgement about *which*
    keys matter: the app is the consumer, and the whole point of forwarding them
    is that a future admission policy can weigh a signal the controller does not
    itself understand.  So every key in the namespace goes, including the ones
    the controller wrote itself (``booking-reference``, the guarantee and
    termination-warning keys) -- a candidate awaiting admission generally has
    none of those, but a re-queued pod may.

    Two bounds apply, both silent-by-design on the value side and logged on the
    key side.  Keys are taken in sorted order and capped at
    ``GALENDS_ANNOTATION_MAX_KEYS`` -- sorted, so the same pod always yields the
    same subset rather than flapping between attempts -- and each value is
    truncated to ``GALENDS_ANNOTATION_MAX_VALUE`` characters.  A truncated value
    is still recognisably itself; a dropped key is not, which is why only the
    latter says so.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    selected = {
        key: value for key, value in annotations.items()
        if key.startswith(GALENDS_PREFIX)
    }
    kept = sorted(selected)[:GALENDS_ANNOTATION_MAX_KEYS]

    dropped = len(selected) - len(kept)
    if dropped:
        # DEBUG, not WARNING: this repeats on every admission attempt for as long
        # as the pod waits, and the same reasoning that puts
        # ``k8s.node_capacity_forced`` at DEBUG applies.  It exists at all so an
        # operator whose annotation never reached the app can find out why.
        log.debug("%s", kv(
            event="pod.annotations_truncated",
            ns=pod.metadata.namespace, pod=pod.metadata.name, count=dropped,
        ))

    return {
        key: str(selected[key])[:GALENDS_ANNOTATION_MAX_VALUE] for key in kept
    }


def utc_iso(dt: datetime) -> str:
    """Render *dt* in the wire format every ``galends/*`` timestamp annotation uses.

    ``YYYY-MM-DDTHH:MM:SSZ``, the format ``docs/POD-ANNOTATIONS.md`` promises
    in-pod consumers.  This is its single definition, so a writer here and the
    diff-and-skip comparisons in ``main`` (which rebuild the string to decide
    whether a re-patch is needed) cannot drift apart into a per-tick re-patch
    loop.

    An aware datetime is normalised to UTC first, so a value that reached us on
    a non-UTC offset is not mislabelled ``Z``.  A naive one is assumed to
    already be UTC — every datetime in this codebase is built with
    ``timezone.utc``, so that is a defensive fallback, not a supported input.
    """
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


# Timezone the human-readable prose renders in — Kubernetes Event messages and
# the ``galends/termination-warning-message`` annotation.  ``None`` means the
# process's local zone (what ``TZ`` sets), which is also the default — so a
# deployment that sets neither variable still renders UTC.  A module global set
# once at startup rather than a threaded parameter: the emitters are reached
# from call sites (``_record_guarantee`` and friends) that carry no ``Config``,
# and this module already holds startup-initialised globals for the API
# clients.
_display_tz: Optional[tzinfo] = None


def set_display_timezone(tz: Optional[tzinfo]) -> None:
    """Set the zone ``local_display`` renders in (``Config.display_timezone``)."""
    global _display_tz
    _display_tz = tz


def format_local(dt: datetime, tz: Optional[tzinfo]) -> str:
    """Render *dt* in *tz* for a human to read, e.g. ``2026-08-21 10:30:16 PDT``.

    The counterpart to ``utc_iso``, and deliberately *not* a replacement for it:
    a stored instant, a ``galends/*`` timestamp annotation and every log field
    stay UTC (``docs/POD-ANNOTATIONS.md`` promises consumers that wire format,
    and ``main``'s diff-and-skip reconciles rebuild those strings to decide
    whether to re-patch).  Only prose a person reads is localised.

    *tz* of ``None`` means the process's local zone, resolved per instant by
    ``astimezone`` — so a daemon that started in PST renders a PDT instant
    correctly rather than freezing the offset it booted with.

    The zone is always named, because a bare local timestamp is ambiguous and
    one labelled ``Z`` would be wrong.  ``%Z`` gives the abbreviation for a
    named zone and can come back empty for a bare fixed offset, so that case
    falls back to the numeric offset.

    A naive instant is assumed to be UTC, matching ``utc_iso`` — ``astimezone``
    would otherwise read it as *local* time, so the two helpers would disagree
    about the same input.  As there, that is a defensive fallback rather than a
    supported input: every datetime in this codebase is built ``timezone.utc``.
    """
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    local = dt.astimezone(tz)
    label = local.strftime("%Z") or local.strftime("%z")
    return f"{local.strftime('%Y-%m-%d %H:%M:%S')} {label}".strip()


def local_display(dt: datetime) -> str:
    """``format_local`` against the startup-configured display zone."""
    return format_local(dt, _display_tz)


# Annotation keys describing the reservation an admitted pod is running under,
# stamped alongside the runtime guarantee (see annotate_runtime_guarantee).
# ``galends/guaranteed-until`` is the end of the guarantee *chain*, which says
# nothing about the pod's own window or how it was obtained — these fill that
# gap so an in-pod widget can distinguish "your 14:00 booking" from "a
# just-in-time lease the controller minted for you", and show how much of a
# booking the pod is actually using.  Informational only, like every other
# galends/* annotation the controller writes: nothing reads them back.
RESERVATION_KIND = "galends/reservation-kind"
RESERVATION_START = "galends/reservation-start"
RESERVATION_END = "galends/reservation-end"
RESERVATION_GPU_COUNT = "galends/reservation-gpu-count"
GPU_CLASS_NAME = "galends/gpu-class-name"

# Write-once: the instant the controller first admitted this pod.  Deliberately
# NOT rewritten when the pod is re-linked to another reservation (adoption /
# lease-to-booking merge) — a re-link is not a new admission, and resetting it
# would restart a session-elapsed clock mid-job.  See ReservationFacts.
ADMITTED_AT = "galends/admitted-at"


@dataclass(frozen=True)
class ReservationFacts:
    """Plain-field digest of the reservation a pod is admitted under.

    Built in ``main`` from a ``schemas.ReservationResponse`` so this module
    stays free of the Pydantic response models — the mirror of the
    ``PodRuntimeView`` convention that keeps ``controller`` free of Kubernetes
    shapes.

    Every field describes the *reservation*, not the pod: ``gpu_count`` is what
    the reservation reserves (which a consumer compares against the pod's own
    request to show "using 1 of the 4 GPUs you booked"), and
    ``start_utc``/``end_utc`` are its own window — not the guarantee chain end
    that ``galends/guaranteed-until`` carries.
    """

    # "booking" | "on_demand" (a just-in-time lease) | "best_effort" (a
    # zero-length stub for a pod that asked for no runtime guarantee)
    kind: str
    start_utc: datetime
    end_utc: datetime
    gpu_count: int
    gpu_class_name: str  # human display name, e.g. "NVIDIA H100 80GB"


# Annotation keys for the informational termination-warning stamped on a pod at
# risk of demand-driven preemption (see main._apply_termination_warnings).  Like
# the runtime-guarantee annotations, these are best-effort and never read back
# to make a decision; the sweep recomputes risk live from reservation state.
TERMINATION_WARNING_AT = "galends/termination-warning-at"
TERMINATION_WARNING_RISK = "galends/termination-warning-risk"
TERMINATION_WARNING_MESSAGE = "galends/termination-warning-message"


def get_pod_termination_warning(pod) -> tuple[Optional[str], Optional[str]]:
    """Return the pod's ``(termination-warning-at, termination-warning-risk)``.

    Either element is ``None`` when its annotation is absent.  Used only to
    diff the desired warning against what the pod already carries, so a
    repeated sweep does not re-patch an unchanged warning.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    return (
        annotations.get(TERMINATION_WARNING_AT),
        annotations.get(TERMINATION_WARNING_RISK),
    )


# Annotation key for the pod's live guarantee status: whether it is still inside
# its runtime guarantee (``"guaranteed"``) or running past it (``"overstay"``).
# It rides alongside the existing ``galends/guaranteed-until`` (the guarantee-end
# instant, kept live) as a general status surface, stamped at admission and
# refreshed as the status changes (guarantee lapsing, adoption/merge).  Like the
# other guarantee/termination annotations it is best-effort and never read back
# to make a decision.
GUARANTEE_STATUS = "galends/guarantee-status"
GUARANTEE_STATUS_GUARANTEED = "guaranteed"
GUARANTEE_STATUS_OVERSTAY = "overstay"


def get_pod_guarantee_status(pod) -> tuple[Optional[str], Optional[str]]:
    """Return the pod's ``(guarantee-status, guaranteed-until)`` annotations.

    Either element is ``None`` when its annotation is absent.  Used only to
    diff the desired status against what the pod already carries, so a repeated
    reconcile does not re-patch an unchanged status.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    return (
        annotations.get(GUARANTEE_STATUS),
        annotations.get("galends/guaranteed-until"),
    )


def get_pod_reservation_facts(pod) -> tuple:
    """Return the pod's five ``galends`` reservation-fact annotations, raw.

    Order matches ``ReservationFacts``: ``(kind, start, end, gpu_count,
    gpu_class_name)``; any element is ``None`` when its annotation is absent.
    Values are the stored strings, **not** parsed — the reconcile in ``main``
    compares them against freshly rendered strings (``utc_iso`` / ``str``), so
    round-tripping through a parse would only introduce a way for the two sides
    to disagree about formatting and re-patch every tick.

    ``galends/admitted-at`` is deliberately absent: it is stamped once at first
    admission and must never be refreshed, so nothing should be diffing it.
    """
    annotations: dict = getattr(pod.metadata, "annotations", None) or {}
    return (
        annotations.get(RESERVATION_KIND),
        annotations.get(RESERVATION_START),
        annotations.get(RESERVATION_END),
        annotations.get(RESERVATION_GPU_COUNT),
        annotations.get(GPU_CLASS_NAME),
    )


# Prefix recorded in a galends/booking-reference value.  Every admitted pod is a
# real reservation now (the lease model requests one just-in-time rather than
# placing onto an ad-hoc block), so there is only one kind.  Construction
# (make_booking_reference) and parsing (parse_booking_reference) live together
# so a renamed prefix cannot silently break occupancy reconstruction.
_BOOKING_REFERENCE_PREFIX = "res-"


def make_booking_reference(reservation_id: int) -> str:
    """Build a ``galends/booking-reference`` value for *reservation_id*.

    The result round-trips through ``parse_booking_reference``.
    """
    return f"{_BOOKING_REFERENCE_PREFIX}{reservation_id}"


def parse_booking_reference(reference: Optional[str]) -> Optional[int]:
    """Extract the reservation id embedded in a ``galends/booking-reference`` value.

    ``"res-42"`` returns ``42``.  Returns ``None`` for an unrecognised prefix,
    a non-integer suffix, or ``None``/empty input.  This is the single key
    used to reconstruct occupancy from the cluster.
    """
    if not reference or not reference.startswith(_BOOKING_REFERENCE_PREFIX):
        return None
    try:
        return int(reference[len(_BOOKING_REFERENCE_PREFIX):])
    except ValueError:
        return None


def pod_has_toleration(pod, key: str, value: str, effect: str) -> bool:
    """Return True if *pod* already carries the named toleration."""
    for t in pod.spec.tolerations or []:
        if t.key == key and t.value == value and t.effect == effect:
            return True
    return False


def _pod_has_any_reservation_toleration(pod, toleration_key: str) -> bool:
    """Return True if *pod* has any toleration whose key equals *toleration_key*.

    Key-only match (any value/effect) — used to identify pods that were
    admitted by this controller regardless of the GPU-class value.
    """
    return any(t.key == toleration_key for t in (pod.spec.tolerations or []))


# Scheduler-message parsing for guard 1 (see is_gpu_gated_pending).
#
# The message is an aggregate of per-node filter verdicts.  kube-scheduler runs
# Filter plugins in a fixed order and records only the *first* one that rejects
# a given node, so a node knocked out by TaintToleration never reaches
# NodeResourcesFit — the constraint that shapes everything below.
_INSUFFICIENT_RE = re.compile(r"Insufficient (\S+)")
_TAINT_BUCKET_RE = re.compile(r"untolerated taint")
# Older kube-scheduler named the offending taint inline —
# "had untolerated taint {key=value: NoSchedule}" — while current versions emit
# an anonymous count ("25 node(s) had untolerated taint(s)").  Both are handled.
_NAMED_TAINT_RE = re.compile(r"untolerated taint \{([^}=:]+)")


def is_gpu_gated_pending(pod, taint_key: str) -> Optional[bool]:
    """Guard 1: is *pod* Pending for something a lease + toleration could fix?

    Inspects ``pod.status.conditions[type=PodScheduled]`` and classifies the
    scheduling failure.  The question is deliberately *not* "is the pod short of
    GPUs" — for an unadmitted candidate the scheduler cannot answer that.  The
    controller's GPU nodes are tainted ``<taint_key>=<class>:NoSchedule``, a
    candidate by definition does not tolerate that yet, and ``TaintToleration``
    runs ahead of ``NodeResourcesFit`` in the default filter order — so every
    node of the pod's own class is rejected on the taint and never produces an
    ``Insufficient nvidia.com/gpu`` verdict at all.  Requiring that string as
    the positive signal held every candidate at "indeterminate" forever on any
    correctly taint-gated cluster.

    So the message is read for what it *can* still say reliably: which blockers
    rule the pod out for reasons a lease cannot fix.

    Returns:
        ``True``  — the scheduler has ruled and named no blocker the controller
                    cannot fix.  Either GPU shortage is named outright (a class
                    whose nodes are untainted), or nodes were rejected on an
                    untolerated taint that may well be ours.  Proceed.
        ``False`` — confirmed blocker we cannot fix: an ``Insufficient
                    <non-GPU-resource>``; or no node was rejected on *any*
                    taint (so our toleration changes nothing) with no GPU
                    shortage named either; or every taint the message names is
                    somebody else's.  Drop the candidate.
        ``None``  — no scheduling verdict yet: the pod is not Pending, carries
                    no ``PodScheduled`` condition, is not ``Unschedulable``, or
                    the message is empty.  Keep the candidate and retry; this
                    is the transient case the MODIFIED fast path in
                    ``pod_watch_loop`` exists to shorten.

    **Known limitation**, inherent to the filter ordering above: a candidate
    blocked by a *second* constraint on its own class's nodes — insufficient
    cpu/memory there, an unrelated taint, an unsatisfiable volume — is
    invisible here, because those nodes never get past the taint filter to
    report it.  Such a pod classifies ``True``, is granted a lease, and stays
    Pending under it.  The backstops are guard 3 (a stuck holder freezes the
    class), the lease's own short expiry, and ``_teardown_ondemand_lease``.
    """
    if get_pod_phase(pod) != "Pending":
        return None

    conditions = (pod.status.conditions or []) if pod.status else []
    scheduled = next((c for c in conditions if c.type == "PodScheduled"), None)
    if scheduled is None or scheduled.status != "False":
        return None
    if scheduled.reason != "Unschedulable":
        return None

    message = scheduled.message or ""
    if not message:
        return None

    # (1) Any non-GPU resource shortage rules the pod out, even when GPU is
    # also short — our toleration alone cannot help it.  Strip trailing
    # punctuation from the match: the scheduler appends commas and periods
    # (e.g. "Insufficient nvidia.com/gpu, 3 Insufficient memory.").
    for m in _INSUFFICIENT_RE.finditer(message):
        if m.group(1).rstrip(".,;)") != "nvidia.com/gpu":
            return False

    # (2) GPU shortage named outright — the unambiguous case, and the only one
    # the pre-taint-aware version of this guard could recognise.  It still
    # occurs for a class whose nodes carry no reservation taint.
    if "Insufficient nvidia.com/gpu" in message:
        return True

    # (3) No node was rejected on a taint at all, and no GPU shortage was
    # named: whatever is blocking this pod, adding a toleration will not move
    # it (a cluster-wide affinity/selector mismatch, an unbindable volume).
    if not _TAINT_BUCKET_RE.search(message):
        return False

    # (4) Taints did reject nodes.  When the scheduler names them, ours has to
    # be among them for a lease to help; when it only counts them
    # (current kube-scheduler), assume it may be and proceed.
    named = {m.group(1).strip() for m in _NAMED_TAINT_RE.finditer(message)}
    if named and taint_key not in named:
        return False

    return True


# ---------------------------------------------------------------------------
# Async wrappers around blocking kubernetes calls
# ---------------------------------------------------------------------------

_T = TypeVar("_T")


async def _run(fn: Callable[..., _T], *args, **kwargs) -> _T:
    """Run a blocking kubernetes-client call on the default thread-pool executor.

    Single choke point for every blocking ``_core_v1`` call made from async code
    (CODE-REVIEW D3b) — the natural place to add ApiException mapping or metrics
    later.  The dedicated watch thread calls the client directly and does not use
    this.
    """
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, functools.partial(fn, *args, **kwargs))


async def read_pod(name: str, namespace: str) -> "k8s_client.V1Pod":
    """Fetch the current pod object (re-read before patching to get fresh state)."""
    log.debug("%s", kv(event="k8s.read_pod", ns=namespace, pod=name))
    return await _run(_core_v1.read_namespaced_pod, name, namespace)


@dataclass(frozen=True)
class ToleratedPodInfo:
    """A point-in-time view of one pod carrying the controller's toleration.

    Returned by ``snapshot_tolerated_pods``; a single cluster LIST yields
    everything the queue-processor tick needs — occupancy reconstruction, the
    claimed-reservation set, and the guard-3 safety interlock — so no per-attempt
    or per-purpose LIST is required.
    """

    namespace: str
    name: str
    uid: str
    gpu_class: str
    booking_reference: Optional[str]
    reservation_id: Optional[int]
    gpu_count: int
    phase: str
    scheduled_false: bool  # PodScheduled condition present with status == "False"
    # Set when the pod has been marked for deletion (``metadata.deletionTimestamp``).
    # A terminating pod is excluded from residency accounting (preemption
    # planning) and is never selected as a preemption victim (it is already on
    # its way out).
    deletion_timestamp: Optional[datetime] = None
    # Value of the REQUIRED_GROUP_LABEL pod label (when the feature is enabled),
    # carried so the adoption planner can enforce the same group constraint used
    # at admission.  None when the feature is disabled or the label is absent.
    group_label: Optional[str] = None
    # The node this pod is bound to (``spec.nodeName``), or None when it has not
    # been scheduled yet.  Carried so per-node GPU accounting can attribute an
    # admitted pod's GPUs to the node it physically occupies.
    node_name: Optional[str] = None
    # Current values of the termination-warning annotations (raw strings), or
    # None when absent.  Carried so the sweep can diff the warning it wants to
    # write against what the pod already has and skip a no-op re-patch, and can
    # detect a stale warning to clear when the pod leaves the at-risk pool.
    termination_warning_at: Optional[str] = None
    termination_warning_risk: Optional[str] = None
    # Current values of the live guarantee-status annotations (raw strings), or
    # None when absent.  Carried so the per-tick reconcile can diff the status it
    # wants against what the pod already has and skip a no-op re-patch.
    guarantee_status: Optional[str] = None
    guaranteed_until: Optional[str] = None
    # Current values of the reservation-fact annotations (raw strings), or None
    # when absent — see get_pod_reservation_facts.  Carried for the same
    # diff-and-skip reason: the facts describe a reservation that can change
    # *underneath* a pod without the pod being re-linked (a window extended in
    # place), and the per-tick reconcile must be able to tell a real change from
    # the overwhelmingly common no-change.
    reservation_kind: Optional[str] = None
    reservation_start: Optional[str] = None
    reservation_end: Optional[str] = None
    reservation_gpu_count: Optional[str] = None
    gpu_class_name: Optional[str] = None


async def snapshot_tolerated_pods(
    toleration_key: str,
    group_label_key: Optional[str] = None,
    group_label_default: Optional[str] = None,
) -> list[ToleratedPodInfo]:
    """Return one ``ToleratedPodInfo`` per pod carrying a *toleration_key* toleration.

    Scans all ``gpu-class``-labelled pods (the same selector as ``PodWatcher`` —
    no new RBAC permission) and shapes each admitted pod into the fields the
    controller needs.  One snapshot per queue-processor tick drives occupancy
    reconstruction, the claimed-reservation set, and guard 3, replacing the
    former per-attempt namespaced counts and the separate guard scans.

    *group_label_key* (the configured REQUIRED_GROUP_LABEL, when enabled) names
    an additional pod label whose value is captured into
    ``ToleratedPodInfo.group_label``; unset ⇒ the field stays None.
    *group_label_default* (the configured DEFAULT_USAGE_GROUP) stands in when the
    pod carries no value for that label — it must be passed wherever routing
    applies the same default, or a pod admitted under the default group would
    read back as group-less and `_group_ok` would reject every reservation for it.
    """
    log.debug("%s", kv(event="k8s.list_pods", selector="gpu-class", purpose="tolerated_snapshot"))
    pod_list = await _run(
        _core_v1.list_pod_for_all_namespaces, label_selector="gpu-class"
    )
    out: list[ToleratedPodInfo] = []
    for pod in pod_list.items:
        if not _pod_has_any_reservation_toleration(pod, toleration_key):
            continue
        conditions = (pod.status.conditions or []) if pod.status else []
        scheduled = next((c for c in conditions if c.type == "PodScheduled"), None)
        booking = get_pod_booking_reference(pod)
        warning_at, warning_risk = get_pod_termination_warning(pod)
        guarantee_status, guaranteed_until = get_pod_guarantee_status(pod)
        res_kind, res_start, res_end, res_gpus, res_class = get_pod_reservation_facts(pod)
        labels = pod.metadata.labels or {}
        out.append(
            ToleratedPodInfo(
                namespace=pod.metadata.namespace,
                name=pod.metadata.name,
                uid=pod.metadata.uid,
                gpu_class=labels.get("gpu-class", ""),
                booking_reference=booking,
                reservation_id=parse_booking_reference(booking),
                gpu_count=get_pod_gpu_count(pod),
                phase=get_pod_phase(pod),
                scheduled_false=(scheduled is not None and scheduled.status == "False"),
                deletion_timestamp=pod.metadata.deletion_timestamp,
                group_label=(
                    (labels.get(group_label_key) or group_label_default)
                    if group_label_key
                    else None
                ),
                node_name=getattr(pod.spec, "node_name", None) if pod.spec else None,
                termination_warning_at=warning_at,
                termination_warning_risk=warning_risk,
                guarantee_status=guarantee_status,
                guaranteed_until=guaranteed_until,
                reservation_kind=res_kind,
                reservation_start=res_start,
                reservation_end=res_end,
                reservation_gpu_count=res_gpus,
                gpu_class_name=res_class,
            )
        )
    log.debug("%s", kv(event="k8s.list_pods_done", purpose="tolerated_snapshot", count=len(out)))
    return out


# ---------------------------------------------------------------------------
# Node capacity
# ---------------------------------------------------------------------------

# Node annotation overriding the GPU capacity the controller reads off a node.
# Unlike every other ``galends/*`` key in this module it is *read* rather than
# written, and it lives on a **node** rather than a pod: it is an operator's
# statement about how many GPUs of that node the reservation system may account
# for, which need not be what the device plugin advertises (a node whose GPUs
# are failing, held back for non-reservation work, or misreported).
FORCE_NODE_CAPACITY = "galends/force-node-capacity"


def get_node_forced_gpu_capacity(node) -> Optional[int]:
    """Read the ``galends/force-node-capacity`` annotation from *node*.

    Returns the GPU count an operator has forced this node to contribute, or
    ``None`` when the annotation is absent, empty, or unusable — in which case
    the caller keeps whatever ``status.allocatable`` reported.

    ``0`` is a **valid** override, and deliberately not rejected the way
    ``get_pod_min_runtime_seconds`` rejects it: masking a node's GPUs from the
    reservation system without cordoning it is the main thing this annotation is
    for, and cordoning is not the same act — it also stops every non-GPU pod and
    is what ``snapshot_node_gpu_inventory`` already treats as "gone entirely".
    A **negative** value is rejected, because a node cannot contribute negative
    capacity and summing one into its class's total would silently eat another
    node's real GPUs.  Junk is rejected for the same tolerant-parsing reason
    ``config.py`` rejects a junk interval — with a WARNING naming the annotation,
    so an operator who set something and saw no effect can find out why.
    """
    annotations: dict = getattr(node.metadata, "annotations", None) or {}
    raw = annotations.get(FORCE_NODE_CAPACITY)
    if raw is None or str(raw).strip() == "":
        return None
    value: Optional[int]
    try:
        value = int(str(raw).strip())
    except (ValueError, TypeError):
        value = None
    if value is None or value < 0:
        log.warning("%s", kv(
            event="k8s.node_capacity_forced_invalid", node=node.metadata.name,
            annotation=FORCE_NODE_CAPACITY, value=raw,
        ))
        return None
    return value


async def snapshot_node_gpu_inventory(
    taint_key: str, gpu_resource: str = "nvidia.com/gpu"
) -> dict[str, dict[str, int]]:
    """Return allocatable GPUs per GPU-class label, broken down **per node**.

    LISTs all nodes and, for each node carrying a *taint_key* taint, records
    ``status.allocatable[gpu_resource]`` under ``{taint_value: {node_name: gpus}}``
    (the GPU-class label mirrors the toleration the controller applies to pods).
    Nodes that are cordoned (``spec.unschedulable``) or being deleted are
    excluded — their GPUs are not placeable.

    A node carrying the ``galends/force-node-capacity`` annotation contributes
    that number instead of its allocatable count (see
    ``get_node_forced_gpu_capacity``).  This is the **only** place the override
    is applied, which is what makes it total: every notion of physical capacity
    in the controller — per-class totals, free capacity, headroom, the capacity
    audit, and the per-node feasibility guards — is derived from this one map.

    This is the per-node primitive: ``snapshot_node_gpu_capacity`` collapses it
    to per-class totals for consumers that only need the aggregate, while
    per-node accounting (whether any *single* node can host a multi-GPU pod)
    reads the breakdown directly.
    """
    log.debug("%s", kv(event="k8s.list_nodes", purpose="gpu_inventory"))
    node_list = await _run(_core_v1.list_node)
    inventory: dict[str, dict[str, int]] = {}
    for node in node_list.items:
        if node.spec and node.spec.unschedulable:
            continue
        if node.metadata.deletion_timestamp is not None:
            continue
        taints = node.spec.taints if (node.spec and node.spec.taints) else []
        classes = {t.value for t in taints if t.key == taint_key and t.value}
        if not classes:
            continue
        allocatable = (node.status.allocatable or {}) if node.status else {}
        raw = allocatable.get(gpu_resource, "0")
        try:
            gpus = int(raw)
        except (ValueError, TypeError):
            log.warning("%s", kv(
                event="k8s.node_allocatable_invalid", node=node.metadata.name,
                resource=gpu_resource, value=raw,
            ))
            gpus = 0
        forced = get_node_forced_gpu_capacity(node)
        if forced is not None:
            # The override replaces the *result* of the allocatable read rather
            # than short-circuiting it, so a node whose allocatable is also
            # unparseable still reports that separately — being overridden is
            # not a reason to stop saying the underlying reading is broken.
            log.debug("%s", kv(
                event="k8s.node_capacity_forced", node=node.metadata.name,
                total=forced,
            ))
            gpus = forced
        for gpu_class in classes:
            inventory.setdefault(gpu_class, {})[node.metadata.name] = gpus
    # The inventory is a nested map, so it is fanned out to one line per class
    # rather than emitted as a dict inside a single field.
    for _cls, _nodes in sorted(inventory.items()):
        log.debug("%s", kv(
            event="k8s.node_inventory", clabel=_cls,
            nodes=len(_nodes), total=sum(_nodes.values()),
        ))
    return inventory


async def snapshot_node_gpu_capacity(
    taint_key: str, gpu_resource: str = "nvidia.com/gpu"
) -> dict[str, int]:
    """Return total allocatable GPUs per GPU-class label, from node taints.

    Thin per-class collapse of ``snapshot_node_gpu_inventory`` (one node LIST,
    summed across the nodes of each class).  Feeds preemption planning's and the
    capacity audit's notion of physical capacity per class; the controller has
    no other source of "how many GPUs actually exist".
    """
    inventory = await snapshot_node_gpu_inventory(taint_key, gpu_resource)
    return {
        gpu_class: sum(per_node.values())
        for gpu_class, per_node in inventory.items()
    }


async def apply_toleration(
    pod_name: str,
    namespace: str,
    pod,
    tol_key: str,
    tol_value: str,
    booking_reference: str,
) -> None:
    """Patch *pod* to add toleration ``tol_key=tol_value:NoSchedule`` and set
    the ``galends/booking-reference`` annotation.

    The booking-reference is the single key from which occupancy is later
    reconstructed (see parse_booking_reference).  The patch preserves all
    existing tolerations; Kubernetes rejects requests that would remove
    tolerations from running pods.
    """
    new_tol = {
        "key": tol_key,
        "operator": "Equal",
        "value": tol_value,
        "effect": "NoSchedule",
    }

    # Serialise existing tolerations into plain dicts for the patch body.
    existing: list[dict] = []
    for t in pod.spec.tolerations or []:
        entry: dict = {
            "key": t.key,
            "operator": t.operator,
            "effect": t.effect,
        }
        if t.value is not None:
            entry["value"] = t.value
        if t.toleration_seconds is not None:
            entry["tolerationSeconds"] = t.toleration_seconds
        existing.append(entry)

    patch = {
        "metadata": {"annotations": {"galends/booking-reference": booking_reference}},
        "spec": {"tolerations": existing + [new_tol]},
    }
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name, patch="toleration",
        tol_key=tol_key, tol_value=tol_value, booking_ref=booking_reference,
    ))
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(
        event="pod.toleration_applied", ns=namespace, pod=pod_name,
        tol_key=tol_key, tol_value=tol_value, booking_ref=booking_reference,
    ))


async def remove_scheduling_gate(
    pod_name: str, namespace: str, pod, gate_name: str
) -> None:
    """Remove *gate_name* from pod.spec.schedulingGates if present.

    Uses the strategic-merge-patch ``$patch: delete`` directive so only the
    named gate is removed; any other gates on the pod are preserved.
    """
    existing_gates = pod.spec.scheduling_gates or []
    if not any(g.name == gate_name for g in existing_gates):
        log.debug("%s", kv(
            event="pod.gate_absent", ns=namespace, pod=pod_name, gate=gate_name,
        ))
        return

    patch = {"spec": {"schedulingGates": [{"name": gate_name, "$patch": "delete"}]}}
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name,
        patch="gate_remove", gate=gate_name,
    ))
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(
        event="pod.gate_removed", ns=namespace, pod=pod_name, gate=gate_name,
    ))


async def annotate_runtime_guarantee(
    pod_name: str,
    namespace: str,
    seconds: int,
    guaranteed_until: datetime,
    facts: ReservationFacts,
    admitted_at: Optional[datetime] = None,
) -> None:
    """Annotate *pod_name* with its runtime guarantee and the reservation behind it.

    Writes ``galends/pod-runtime-limit-seconds`` (the guaranteed duration in
    seconds, consumed by in-pod countdown widgets), ``galends/guaranteed-until``
    (the same instant as an absolute UTC ISO-8601 timestamp), and
    ``galends/guarantee-status`` (``"guaranteed"`` — recording a guarantee always
    means the pod is inside one; the reconcile in ``main`` flips this to
    ``"overstay"`` once the guarantee lapses).

    It also stamps *facts* — the reservation's kind, own window, reserved GPU
    count, and display name of its GPU class — in the **same patch**, so the
    whole descriptive set costs no extra API call.  Because these describe the
    reservation the pod is currently linked to, every caller that re-links a pod
    (adoption, lease-to-booking merge) must call this again with the new
    reservation or the stamps would keep describing the old one.
    ``admitted_at`` is passed only on a pod's **first** admission, and is
    omitted (left at whatever the pod already carries) on those re-links.

    Re-linking is not the only way the facts can go stale: the *same*
    reservation can be mutated underneath the pod (a lease window extended in
    place), which reaches none of those callers.  ``annotate_reservation_facts``
    plus the per-tick ``main._apply_reservation_facts`` reconcile cover that
    case; this function stays the admission/re-link writer.

    Informational only: this never patches ``spec.activeDeadlineSeconds`` —
    demand-driven preemption enforces nothing through a Kubernetes-side
    deadline, and never reads these annotations back to make a decision; it
    recomputes the guarantee live from reservation state
    (``ControllerState.guarantee_end``).
    """
    until_str = utc_iso(guaranteed_until)
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name, patch="runtime_guarantee",
        guarantee_s=seconds, until=until_str,
    ))
    annotations = {
        "galends/pod-runtime-limit-seconds": str(seconds),
        "galends/guaranteed-until": until_str,
        GUARANTEE_STATUS: GUARANTEE_STATUS_GUARANTEED,
        RESERVATION_KIND: facts.kind,
        RESERVATION_START: utc_iso(facts.start_utc),
        RESERVATION_END: utc_iso(facts.end_utc),
        RESERVATION_GPU_COUNT: str(facts.gpu_count),
        GPU_CLASS_NAME: facts.gpu_class_name,
    }
    if admitted_at is not None:
        annotations[ADMITTED_AT] = utc_iso(admitted_at)
    patch = {"metadata": {"annotations": annotations}}
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(
        event="pod.guarantee_recorded", ns=namespace, pod=pod_name,
        guarantee_s=seconds, until=until_str,
    ))


async def annotate_reservation_facts(
    pod_name: str,
    namespace: str,
    facts: ReservationFacts,
) -> None:
    """Re-stamp *pod_name*'s reservation-fact annotations from *facts*.

    ``annotate_runtime_guarantee`` writes these at admission and on every
    **re-link** (adoption, lease-to-booking merge), which covers every way the
    pod's reservation could change *identity*.  This covers the remaining way it
    can change *content*: the same reservation being mutated underneath the pod
    — an on-demand lease whose window is extended in place, which re-links
    nothing and so reaches none of those callers.  Without it the pod would keep
    advertising its pre-extension ``galends/reservation-end`` while
    ``galends/guaranteed-until`` moved forward, and a consumer reading both
    would see them contradict each other.

    Writes only the five fact keys.  It deliberately does **not** touch
    ``galends/guarantee-status`` / ``-guaranteed-until`` (owned by
    ``annotate_guarantee_status``, which reconciles them from live chain-aware
    state) or ``galends/admitted-at`` (stamped once, at first admission — a
    session-elapsed clock that must never restart mid-job).

    Informational only, like every other ``galends`` stamp: never enforced
    Kubernetes-side and never read back to make a decision.
    """
    end_str = utc_iso(facts.end_utc)
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name,
        patch="reservation_facts", end=end_str,
    ))
    patch = {
        "metadata": {
            "annotations": {
                RESERVATION_KIND: facts.kind,
                RESERVATION_START: utc_iso(facts.start_utc),
                RESERVATION_END: end_str,
                RESERVATION_GPU_COUNT: str(facts.gpu_count),
                GPU_CLASS_NAME: facts.gpu_class_name,
            }
        },
    }
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(
        event="pod.facts_refreshed", ns=namespace, pod=pod_name, end=end_str,
    ))


async def annotate_guarantee_status(
    pod_name: str,
    namespace: str,
    status: str,
    guaranteed_until: Optional[datetime],
) -> None:
    """Update *pod_name*'s live ``galends/guarantee-status`` (+ ``guaranteed-until``).

    Writes ``galends/guarantee-status`` (``"guaranteed"`` | ``"overstay"``) and,
    **only when** *guaranteed_until* is provided, refreshes
    ``galends/guaranteed-until`` to that absolute UTC ISO-8601 instant.  For an
    overstay pod *guaranteed_until* is ``None`` so the existing (now-past)
    ``guaranteed-until`` value is left frozen — only the status key flips.
    Informational only, mirroring ``annotate_runtime_guarantee``: nothing is
    enforced Kubernetes-side and these are never read back to make a decision.
    """
    annotations: dict = {GUARANTEE_STATUS: status}
    if guaranteed_until is not None:
        annotations["galends/guaranteed-until"] = utc_iso(guaranteed_until)
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name,
        patch="guarantee_status", gstatus=status,
    ))
    patch = {"metadata": {"annotations": annotations}}
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(event="pod.guarantee_status", ns=namespace, pod=pod_name, gstatus=status))


async def annotate_termination_warning(
    pod_name: str,
    namespace: str,
    terminate_at: datetime,
    risk: str,
    message: str,
) -> None:
    """Stamp *pod_name* with the informational termination-warning annotations.

    Writes ``galends/termination-warning-at`` (the projected preemption instant,
    absolute UTC ISO-8601, matching ``guaranteed-until``), ``-risk`` (a value in
    (0, 1] as a pre-rounded string), and ``-message`` (human-readable).  Purely
    informational — nothing is enforced Kubernetes-side and these are never read
    back to make a decision (the sweep recomputes risk live from reservation
    state); a widget should treat them as a best-effort heads-up.
    """
    at_str = utc_iso(terminate_at)
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name,
        patch="termination_warning", at=at_str, risk=risk,
    ))
    patch = {
        "metadata": {
            "annotations": {
                TERMINATION_WARNING_AT: at_str,
                TERMINATION_WARNING_RISK: risk,
                TERMINATION_WARNING_MESSAGE: message,
            }
        },
    }
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(
        event="pod.termination_warned", ns=namespace, pod=pod_name, at=at_str, risk=risk,
    ))


async def clear_termination_warning(pod_name: str, namespace: str) -> None:
    """Remove the termination-warning annotations from *pod_name*.

    Retraction path: the pod left the at-risk pool (its user re-booked, demand
    evaporated, or it was adopted), so a stale "you may be preempted" stamp
    would mislead.  Setting each annotation value to ``None`` in a strategic
    merge patch deletes the key.
    """
    log.debug("%s", kv(
        event="k8s.patch_pod", ns=namespace, pod=pod_name,
        patch="termination_warning_clear",
    ))
    patch = {
        "metadata": {
            "annotations": {
                TERMINATION_WARNING_AT: None,
                TERMINATION_WARNING_RISK: None,
                TERMINATION_WARNING_MESSAGE: None,
            }
        },
    }
    await _run(_core_v1.patch_namespaced_pod, pod_name, namespace, patch)
    log.info("%s", kv(event="pod.termination_warning_cleared", ns=namespace, pod=pod_name))


async def _emit_pod_event(
    pod_uid: str,
    pod_name: str,
    namespace: str,
    *,
    name_prefix: str,
    reason: str,
    action: str,
    message: str,
    event_type: str = "Normal",
) -> None:
    """Create a Kubernetes Event linked to the pod identified by *pod_uid*.

    Shared body for the runtime-guarantee, preemption, and cancellation
    emitters (CODE-REVIEW D3c), which differ only in *name_prefix* / *reason*
    / *action* / *message* / *event_type*.  Uses ``generate_name`` so
    re-emitting for the same pod never 409s (B10).

    Takes the pod **uid** rather than the pod object because that is the only
    field of it this needs (the ``involvedObject`` reference), and the
    lease-denial and admission-paused emitters have a uid in hand without a
    pod: their candidate was never admitted, so re-reading the pod purely to
    fill in an event would be a second API call for a field the caller already
    knows.
    """
    now = datetime.now(timezone.utc)
    event = k8s_client.CoreV1Event(
        metadata=k8s_client.V1ObjectMeta(
            generate_name=name_prefix,
            namespace=namespace,
        ),
        involved_object=k8s_client.V1ObjectReference(
            api_version="v1",
            kind="Pod",
            name=pod_name,
            namespace=namespace,
            uid=pod_uid,
        ),
        reason=reason,
        message=message,
        type=event_type,
        first_timestamp=now,
        last_timestamp=now,
        count=1,
        reporting_component="gpu-reservation-controller",
        action=action,
    )
    log.debug("%s", kv(
        event="k8s.create_event", ns=namespace, pod=pod_name, reason=reason,
    ))
    await _run(_core_v1.create_namespaced_event, namespace, event)


async def emit_runtime_guaranteed_event(
    pod,
    pod_name: str,
    namespace: str,
    seconds: int,
    guaranteed_until: datetime,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='RuntimeGuaranteed'."""
    minutes, secs = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    human = (
        f"{hours}h{minutes:02d}m{secs:02d}s"
        if hours
        else f"{minutes}m{secs:02d}s"
    )
    # The Event message reads in local time (a person reads it); the log field
    # stays UTC, because it joins to the app's own log lines and to the
    # galends/guaranteed-until annotation this same admission writes.
    until_str = utc_iso(guaranteed_until)
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-guarantee-",
        reason="RuntimeGuaranteed",
        action="GuaranteeRuntime",
        message=(
            f"GPU access guaranteed for {human}, until "
            f"{local_display(guaranteed_until)}. The pod may "
            f"keep running after that, but can be preempted if reserved capacity "
            f"is needed."
        ),
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name,
        reason="RuntimeGuaranteed", guarantee_s=seconds, until=until_str,
    ))


async def emit_best_effort_admitted_event(
    pod,
    pod_name: str,
    namespace: str,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='BestEffortAdmitted'.

    The counterpart to ``RuntimeGuaranteed`` for a pod that asked for no
    guarantee.  It gets its own Event rather than a degenerate guarantee one:
    that message would read "GPU access guaranteed for 0m00s, until <the instant
    the pod started>", which is both nonsense and alarming to the one person who
    reads it — the pod's owner, running ``kubectl describe``.

    ``Normal``, not ``Warning``: nothing has gone wrong.  The pod got exactly
    what it asked for, and the message says what that means in practice.
    """
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-best-effort-",
        reason="BestEffortAdmitted",
        action="AdmitBestEffort",
        message=(
            "Admitted on a best-effort basis at this pod's own request "
            "(galends/runtime-guarantee=none). GPU access is not guaranteed for "
            "any length of time and no Service Units are charged: the pod may be "
            "preempted as soon as any other job needs the capacity. Remove the "
            "annotation, or book a reservation, to get a guaranteed runtime."
        ),
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name,
        reason="BestEffortAdmitted",
    ))


async def emit_lease_denied_event(
    pod_uid: str,
    pod_name: str,
    namespace: str,
    detail: str,
    *,
    gpu_class: str,
    gpu_count: int,
) -> None:
    """Create a ``Warning`` Event linked to a pod whose JIT lease was refused.

    The app answers an infeasible on-demand ask with a 409 whose ``detail``
    states *why* — "Only 2 GPU(s) available for this group at 2026-08-21 14:00
    (group ceiling: 4)", an exhausted SU budget, a group the user is not in.
    Until this existed that reason reached the controller's log and stopped
    there, so the pod's owner saw only an indefinitely Pending pod with no
    account of what was blocking it.  Surfacing it as an Event puts it where a
    user already looks (``kubectl describe pod``) without granting the pod
    itself any API access.

    ``Warning`` rather than ``Normal`` — the pod is not running and will not
    until something changes — which also matches how kube-scheduler reports the
    neighbouring condition, ``FailedScheduling``.  Informational only: the
    controller keeps retrying on its own cadence either way.
    """
    await _emit_pod_event(
        pod_uid,
        pod_name,
        namespace,
        name_prefix="gpu-lease-denied-",
        reason="OnDemandLeaseDenied",
        action="RequestOnDemandLease",
        event_type="Warning",
        message=(
            f"On-demand GPU lease for {gpu_count} x {gpu_class} was denied by the "
            f"reservation service: {detail}. The pod stays Pending; the controller "
            f"will keep retrying."
        ),
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name,
        reason="OnDemandLeaseDenied", clabel=gpu_class, gpus=gpu_count,
    ))


async def emit_admission_paused_event(
    pod_uid: str,
    pod_name: str,
    namespace: str,
    message: str,
    *,
    gpu_class: str,
    guard: int,
) -> None:
    """Create a ``Warning`` Event on a pod whose on-demand admission is paused.

    The sibling of ``emit_lease_denied_event`` for the other way a JIT candidate
    sits Pending: never offered to the app at all, because a class-wide gate —
    guard 1b (no schedulable node), guard 3's stuck-holder interlock or guard
    4's capacity overcommit — holds every on-demand pod of its GPU class until
    something outside the pod changes.  An operator hears about that from the
    ``ondemand.gated`` log line; this is how the pod's owner does.

    *message* is rendered by the caller (``main._admission_paused_message``),
    which knows what each guard means; this only writes it.  ``Warning`` for
    the same reason as the denial: the pod is not running and will not until
    something changes.
    """
    await _emit_pod_event(
        pod_uid,
        pod_name,
        namespace,
        name_prefix="gpu-admission-paused-",
        reason="OnDemandAdmissionPaused",
        action="HoldOnDemandAdmission",
        event_type="Warning",
        message=message,
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name,
        reason="OnDemandAdmissionPaused", clabel=gpu_class, guard=guard,
    ))


# Warning Events telling a pending pod's owner that something *about the pod*
# stops the controller admitting it -- the siblings of OnDemandLeaseDenied and
# OnDemandAdmissionPaused, which report the app refusing or a class being
# paused.  Each reason maps to the Event's ``action`` (what the controller was
# attempting) and its ``generateName`` prefix.
LEASE_REJECTED_REASON = "OnDemandLeaseRejected"
UNKNOWN_GPU_CLASS_REASON = "UnknownGpuClass"
NO_RESERVATION_REASON = "NoReservation"
ANNOTATION_IGNORED_REASON = "AnnotationIgnored"

_POD_PROBLEM_EVENTS: dict[str, tuple[str, str]] = {
    LEASE_REJECTED_REASON: ("RequestOnDemandLease", "gpu-lease-rejected-"),
    UNKNOWN_GPU_CLASS_REASON: ("AdmitPod", "gpu-unknown-class-"),
    NO_RESERVATION_REASON: ("AdmitPod", "gpu-no-reservation-"),
    ANNOTATION_IGNORED_REASON: ("ReadAnnotations", "gpu-annotation-ignored-"),
}

# events.k8s.io/v1's limit on an Event's note; the core/v1 API this module
# writes through does not enforce one, but tooling reading the newer API does.
_EVENT_MESSAGE_MAX_CHARS = 1024


async def emit_pod_problem_event(
    pod_uid: str,
    pod_name: str,
    namespace: str,
    message: str,
    *,
    reason: str,
    gpu_class: Optional[str] = None,
    gpu_count: Optional[int] = None,
) -> None:
    """Create a ``Warning`` Event on a pod the controller cannot admit as written.

    *reason* is one of the four above:

    - ``OnDemandLeaseRejected`` -- the reservation app answered the pod's lease
      ask with a 404: it does not recognise the user, usage group or GPU class
      the ask named, all of which come from the pod (its namespace, its group
      label or annotation, its ``gpu-class`` label).
    - ``UnknownGpuClass`` -- the pod's ``gpu-class`` label names no class the
      reservation app knows, so no path can admit it.
    - ``NoReservation`` -- no reservation matches the pod and it does not
      qualify for on-demand admission either.
    - ``AnnotationIgnored`` -- one of its ``galends/*`` job-input annotations
      was invalid, or asks for something this deployment does not offer.

    *message* is rendered by the caller (``main``), which knows what each means
    to the pod's owner; this only writes it -- capped at the 1024 characters
    ``events.k8s.io/v1`` allows a note, since it quotes the app's reason and
    the pod's own labels and annotations, whose lengths nothing here controls.
    ``Warning`` for the same reason as ``OnDemandLeaseDenied``: the pod is not
    running, and will not until something changes -- here, usually the pod
    itself.
    """
    action, name_prefix = _POD_PROBLEM_EVENTS[reason]
    if len(message) > _EVENT_MESSAGE_MAX_CHARS:
        message = message[: _EVENT_MESSAGE_MAX_CHARS - 1] + "…"
    await _emit_pod_event(
        pod_uid,
        pod_name,
        namespace,
        name_prefix=name_prefix,
        reason=reason,
        action=action,
        event_type="Warning",
        message=message,
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name, reason=reason,
        clabel=gpu_class, gpus=gpu_count,
    ))


async def delete_pod(name: str, namespace: str) -> None:
    """Delete a pod by name and namespace.

    A 404 response is silently ignored — the pod may have already been removed
    by the time the controller processes the cancellation.
    """
    log.debug("%s", kv(event="k8s.delete_pod", ns=namespace, pod=name))
    try:
        await _run(_core_v1.delete_namespaced_pod, name, namespace)
        log.info("%s", kv(event="pod.deleted", ns=namespace, pod=name))
    except ApiException as exc:
        if exc.status == 404:
            log.debug("%s", kv(event="pod.already_gone", ns=namespace, pod=name, status=404))
            return
        raise


async def emit_preempted_event(
    pod,
    pod_name: str,
    namespace: str,
    message: str,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='Preempted'.

    Emitted when the preemption sweep deletes a pod running past its runtime
    guarantee to recover capacity.  The caller builds *message* (it knows how
    long the pod overstayed).
    """
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-preempt-",
        reason="Preempted",
        action="PreemptPod",
        message=message,
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name, reason="Preempted",
    ))


async def emit_reservation_cancelled_event(
    pod,
    pod_name: str,
    namespace: str,
    cancelled_by_desc: str,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='ReservationCancelled'."""
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-rescancel-",
        reason="ReservationCancelled",
        action="EvictPod",
        message=f"Pod evicted: GPU reservation cancelled {cancelled_by_desc}.",
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name, reason="ReservationCancelled",
    ))


async def emit_reservation_reassigned_event(
    pod,
    pod_name: str,
    namespace: str,
    new_owner_desc: str,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='ReservationReassigned'.

    Emitted when a reservation is reassigned to a new owner ("adoption") and the
    prior owner's admitted pod is evicted so the new owner can claim the window.
    """
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-resadopt-",
        reason="ReservationReassigned",
        action="EvictPod",
        message=f"Pod evicted: GPU reservation reassigned {new_owner_desc}.",
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name, reason="ReservationReassigned",
    ))


async def emit_overstay_relinked_event(
    pod,
    pod_name: str,
    namespace: str,
    reservation_id: int,
    guaranteed_until: datetime,
) -> None:
    """Create a Kubernetes Event linked to *pod* with reason='OverstayRelinked'.

    Emitted when an overstay pod (running past its runtime guarantee) is re-linked
    to a reservation the same user has since booked, so it is no longer treated as
    overstay.  Distinct from ReservationReassigned (which evicts a pod on an
    owner change) — here the *same* pod keeps running under a new reservation id.
    """
    until_str = utc_iso(guaranteed_until)
    await _emit_pod_event(
        pod.metadata.uid,
        pod_name,
        namespace,
        name_prefix="gpu-relink-",
        reason="OverstayRelinked",
        action="RelinkPod",
        message=(
            f"Pod re-linked to GPU reservation #{reservation_id}; no longer "
            f"overstay. GPU access guaranteed until "
            f"{local_display(guaranteed_until)}."
        ),
    )
    log.info("%s", kv(
        event="k8s.event_emitted", ns=namespace, pod=pod_name,
        reason="OverstayRelinked", rid=reservation_id, until=until_str,
    ))


# ---------------------------------------------------------------------------
# Pod event stream
# ---------------------------------------------------------------------------


# Watch-loop tuning.  Module constants (not env vars) like the values they
# replace; the PodWatcher constructor takes keyword overrides as test seams.
_WATCH_TIMEOUT_S = 270          # server-side clean close, beats LB idle timeouts
_WATCH_RESYNC_INTERVAL_S = 600  # full re-LIST cadence (routing self-heal)
_WATCH_QUEUE_MAXSIZE = 4096     # backpressure bound; must exceed labeled-pod count
_WATCH_RETRY_DELAY_S = 5        # fixed backoff between failed cycles


class PodWatcher:
    """Async-generator source of pod watch events for all namespaces.

    Uses a background thread running ``kubernetes.watch.Watch`` (which issues
    a long-poll HTTP stream) and forwards events to the asyncio event loop via
    ``loop.call_soon_threadsafe``.  The watch thread automatically reconnects
    after any error.

    Reconnect protocol: the thread tracks the ``resourceVersion`` of every
    event (bookmarks included, requested via ``allow_watch_bookmarks``), so a
    clean stream close — the server honouring ``timeout_seconds`` every ~4.5
    min — *resumes* the watch where it left off instead of re-LISTing and
    replaying the world as ADDED.  A full LIST+replay happens only at start,
    after an error, on HTTP 410 (resourceVersion expired — immediate, no
    backoff), and every ``_WATCH_RESYNC_INTERVAL_S`` as a deliberate resync:
    the periodic replay is the self-heal for a pod whose ADDED was never seen
    (nothing else discovers unrouted pods), and consumers treat replays
    idempotently (see the fast-path cooldown guard, B8).

    The event queue is bounded; if the consumer stalls, the *oldest* event is
    dropped (newest state supersedes it, and the next resync heals the gap)
    rather than growing without limit.

    Usage::

        watcher = PodWatcher(label_selector="gpu-class")
        async for event_type, pod in watcher.events():
            ...  # event_type is "ADDED", "MODIFIED", or "DELETED"
    """

    def __init__(
        self,
        label_selector: str = "gpu-class",
        *,
        resync_interval_s: float = _WATCH_RESYNC_INTERVAL_S,
        queue_maxsize: int = _WATCH_QUEUE_MAXSIZE,
        watch_timeout_s: int = _WATCH_TIMEOUT_S,
        retry_delay_s: float = _WATCH_RETRY_DELAY_S,
    ) -> None:
        self._label_selector = label_selector
        self._resync_interval_s = resync_interval_s
        self._queue_maxsize = queue_maxsize
        self._watch_timeout_s = watch_timeout_s
        self._retry_delay_s = retry_delay_s
        self._watch: Optional[watch.Watch] = None
        self._dropped = 0

    def _offer(self, queue: "asyncio.Queue", item: tuple[str, object]) -> None:
        """Enqueue *item*, dropping the oldest event if the queue is full.

        Always invoked on the event-loop thread (via ``call_soon_threadsafe``),
        so the full/drop/put triple cannot interleave with the consumer's get.
        Dropping the *oldest* is right for a level-triggered consumer — newer
        state for a pod supersedes older — and the periodic resync re-LIST
        heals whatever a drop lost.
        """
        if queue.full():
            try:
                queue.get_nowait()  # drop the OLDEST event
            except asyncio.QueueEmpty:  # pragma: no cover — full ⇒ non-empty
                pass
            self._dropped += 1
            if self._dropped == 1 or self._dropped % 100 == 0:
                log.warning("%s", kv(
                    event="k8s.watch_dropped", dropped=self._dropped,
                ))
        queue.put_nowait(item)

    def _log_watch_failure(self, fail_count: int, exc: Exception) -> None:
        """Throttled failure logging: WARNING on the first failure and every
        120th (~10 min at the 5 s retry), DEBUG in between."""
        if fail_count == 1 or fail_count % 120 == 0:
            log.warning("%s", kv(
                event="k8s.watch_error", fails=fail_count, err=exc,
                retry_s=self._retry_delay_s,
            ))
        else:
            log.debug("%s", kv(
                event="k8s.watch_ended", err=exc, retry_s=self._retry_delay_s,
            ))

    async def events(self) -> AsyncIterator[tuple[str, object]]:
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue[tuple[str, object]] = asyncio.Queue(
            maxsize=self._queue_maxsize
        )
        stop_event = threading.Event()

        def _run_watch() -> None:
            """Blocking LIST/WATCH loop; runs in a dedicated daemon thread."""
            fail_count = 0
            rv: Optional[str] = None    # None ⇒ the next cycle must LIST
            relist_reason = "start"
            last_list = 0.0             # time.monotonic() of the last LIST
            while not stop_event.is_set():
                try:
                    resync_due = rv is not None and (
                        time.monotonic() - last_list >= self._resync_interval_s
                    )
                    if rv is None or resync_due:
                        if resync_due:
                            relist_reason = "resync"
                        # LIST — surfaces pods that exist before we started (or
                        # whose events a gap swallowed) by replaying them as ADDED.
                        log.debug("%s", kv(
                            event="k8s.list_pods", selector=self._label_selector,
                            purpose="watch_seed", reason=relist_reason,
                        ))
                        pod_list = _core_v1.list_pod_for_all_namespaces(
                            label_selector=self._label_selector
                        )
                        log.debug("%s", kv(
                            event="k8s.list_pods_done", purpose="watch_seed",
                            count=len(pod_list.items),
                            rv=pod_list.metadata.resource_version,
                        ))
                        for pod in pod_list.items:
                            loop.call_soon_threadsafe(self._offer, queue, ("ADDED", pod))
                        rv = pod_list.metadata.resource_version
                        last_list = time.monotonic()
                        mode = "seed"
                    else:
                        # Clean close with a live rv: resume exactly where the
                        # last stream left off — no LIST, no replay.
                        mode = "resume"

                    w = watch.Watch()
                    self._watch = w
                    # WATCH — stream incremental events from rv onward.
                    # timeout_seconds asks the API server to close the stream
                    # cleanly before any proxy/LB idle timeout fires; it also
                    # disables the client's internal silent retry, which is what
                    # guarantees a 410 surfaces here as ApiException rather than
                    # being swallowed (do not remove it).
                    log.debug("%s", kv(
                        event="k8s.watch_open", selector=self._label_selector,
                        rv=rv, timeout_s=self._watch_timeout_s, mode=mode,
                    ))
                    progressed = False
                    for event in w.stream(
                        _core_v1.list_pod_for_all_namespaces,
                        label_selector=self._label_selector,
                        resource_version=rv,
                        timeout_seconds=self._watch_timeout_s,
                        allow_watch_bookmarks=True,
                    ):
                        if stop_event.is_set():
                            w.stop()
                            return
                        if not isinstance(event, dict):
                            # Newer clients can yield None for undecodable lines.
                            continue
                        if not progressed:
                            # The stream demonstrably works — only now reset the
                            # failure counter.  (Resetting right after the LIST,
                            # as before, defeated the throttle whenever the LIST
                            # succeeded but the stream kept failing.)
                            progressed = True
                            fail_count = 0
                        if event.get("type") == "BOOKMARK":
                            # Bookmark objects are raw dicts (never deserialized,
                            # so no model attributes); they exist purely to
                            # advance rv and are not forwarded to the consumer.
                            new_rv = (
                                (event.get("raw_object") or {})
                                .get("metadata", {})
                                .get("resourceVersion")
                            )
                            if new_rv:
                                rv = new_rv
                            log.debug("%s", kv(event="k8s.watch_bookmark", rv=rv))
                            continue
                        obj = event["object"]
                        new_rv = getattr(
                            getattr(obj, "metadata", None), "resource_version", None
                        )
                        if new_rv:
                            rv = new_rv
                        log.debug("%s", kv(
                            event="k8s.watch_event", watch_event=event["type"],
                            ns=obj.metadata.namespace, pod=obj.metadata.name,
                        ))
                        loop.call_soon_threadsafe(self._offer, queue, (event["type"], obj))
                    # Clean close: the server honoured timeout_seconds.  A
                    # healthy cycle even if it carried no events.
                    fail_count = 0

                except ApiException as exc:
                    if exc.status == 410:
                        # resourceVersion expired — the standard protocol signal
                        # to re-LIST immediately.  Not a fault: no backoff, no
                        # failure count.
                        log.info("%s", kv(event="k8s.watch_expired", rv=rv))
                        rv = None
                        relist_reason = "expired"
                        continue
                    fail_count += 1
                    rv = None  # rv provenance is not trustworthy after a failure
                    relist_reason = "error"
                    self._log_watch_failure(fail_count, exc)
                    # Interruptible sleep: a set stop_event returns immediately.
                    if stop_event.wait(self._retry_delay_s):
                        return
                except Exception as exc:  # noqa: BLE001
                    fail_count += 1
                    rv = None  # rv provenance is not trustworthy after a failure
                    relist_reason = "error"
                    self._log_watch_failure(fail_count, exc)
                    # Interruptible sleep: a set stop_event returns immediately.
                    if stop_event.wait(self._retry_delay_s):
                        return

        # Run the blocking watch in a dedicated daemon thread rather than the
        # shared default executor: it never returns on its own, so it must not
        # occupy an executor slot every other K8s call contends for, and as a
        # daemon it cannot hang interpreter exit / test teardown.  The stop_event
        # lets us unwind the reconnect loop promptly when the consumer stops
        # iterating (B7).
        thread = threading.Thread(target=_run_watch, name="pod-watch", daemon=True)
        thread.start()

        try:
            while True:
                event_type, pod = await queue.get()
                yield event_type, pod
        finally:
            stop_event.set()
            # Best-effort prompt unblock: on newer kubernetes clients
            # Watch.stop() shuts the socket down and the thread exits at once;
            # on v29 it is a flag write and a quiet stream parks the thread
            # until the server timeout — harmless, it is a daemon thread.
            w = self._watch
            if w is not None:
                try:
                    w.stop()
                except Exception:  # noqa: BLE001 — teardown must never raise
                    pass


# ---------------------------------------------------------------------------
# Singleton lease — duplicate-instance guard (not leader election)
# ---------------------------------------------------------------------------

#: Name of the coordination Lease every controller instance contends for.  One
#: controller per namespace: the chart deploys exactly one release per
#: namespace, so a fixed name needs no configuration.
LEASE_NAME = "gpu-reservation-controller"


@dataclass(frozen=True)
class LeaseOutcome:
    """Result of a singleton-lease acquire/renew attempt.

    Errors are returned, never raised: every caller's response to an API
    failure is the same fail-open "keep running and retry", and a result type
    makes that impossible to forget.
    """

    status: str  # "acquired" | "held_by_other" | "lost" | "error"
    holder: Optional[str] = None  # the other instance's identity, when known
    age_s: Optional[int] = None   # seconds since the holder last renewed
    mode: Optional[str] = None    # "created" | "reacquired" | "takeover" | "renewed"
    err: Optional[str] = None


def _lease_age_seconds(lease, now: datetime) -> Optional[int]:
    """Seconds since *lease* was last renewed, or None if it never was."""
    renewed = getattr(lease.spec, "renew_time", None)
    if renewed is None:
        return None
    if renewed.tzinfo is None:  # defensive: the client returns aware datetimes
        renewed = renewed.replace(tzinfo=timezone.utc)
    return int((now - renewed).total_seconds())


def _lease_resource_version(lease) -> Optional[str]:
    """The resourceVersion of a Lease we just read, or None if absent."""
    meta = getattr(lease, "metadata", None)
    rv = getattr(meta, "resource_version", None) if meta is not None else None
    return str(rv) if rv else None


def _lease_body(holder: str, duration_s: int, now: datetime, *, acquire: bool,
                transitions: int = 0, resource_version: Optional[str] = None):
    """Build a Lease object claiming (or renewing) the singleton lock.

    *resource_version* must be carried over from the Lease we just read
    whenever this body is going to be PUT: the apiserver rejects an update
    whose ``metadata.resourceVersion`` is unset with a 422 ("must be specified
    for an update"), so a body built without it can be created but never
    replaced.  It doubles as the optimistic-concurrency token — a write that
    raced another instance's fails 409 rather than silently clobbering it,
    and the next tick re-reads and re-decides.
    """
    spec = k8s_client.V1LeaseSpec(
        holder_identity=holder,
        lease_duration_seconds=duration_s,
        renew_time=now,
        lease_transitions=transitions,
    )
    if acquire:
        spec.acquire_time = now
    return k8s_client.V1Lease(
        metadata=k8s_client.V1ObjectMeta(
            name=LEASE_NAME, resource_version=resource_version
        ),
        spec=spec,
    )


async def acquire_singleton_lease(
    namespace: str, holder: str, duration_s: int
) -> LeaseOutcome:
    """Claim the singleton Lease for *holder*, or report who holds it.

    Returns ``held_by_other`` only when another identity holds an **unexpired**
    lease — the affirmative "a second controller is running" signal.  An
    expired lease is taken over (the previous holder crashed), and our own
    lease is simply refreshed, so a container restart of the same pod recovers
    immediately rather than waiting out the duration.
    """
    now = datetime.now(timezone.utc)
    try:
        try:
            lease = await _run(
                _coordination_v1.read_namespaced_lease, LEASE_NAME, namespace
            )
        except ApiException as exc:
            if exc.status != 404:
                raise
            await _run(
                _coordination_v1.create_namespaced_lease,
                namespace,
                _lease_body(holder, duration_s, now, acquire=True),
            )
            log.debug("%s", kv(event="k8s.lease_write", name=LEASE_NAME, mode="created"))
            return LeaseOutcome(status="acquired", holder=holder, mode="created")

        current = getattr(lease.spec, "holder_identity", None)
        age = _lease_age_seconds(lease, now)
        expiry = getattr(lease.spec, "lease_duration_seconds", None) or duration_s
        transitions = getattr(lease.spec, "lease_transitions", 0) or 0

        if current == holder:
            mode = "reacquired"
        elif age is None or age > expiry:
            mode = "takeover"
            transitions += 1
        else:
            return LeaseOutcome(status="held_by_other", holder=current, age_s=age)

        await _run(
            _coordination_v1.replace_namespaced_lease,
            LEASE_NAME,
            namespace,
            _lease_body(
                holder, duration_s, now, acquire=True, transitions=transitions,
                resource_version=_lease_resource_version(lease),
            ),
        )
        log.debug("%s", kv(event="k8s.lease_write", name=LEASE_NAME, mode=mode))
        return LeaseOutcome(
            status="acquired", holder=holder, mode=mode,
            age_s=age if mode == "takeover" else None,
        )
    except Exception as exc:  # noqa: BLE001 — fail open, the caller keeps running
        return LeaseOutcome(status="error", err=str(exc))


async def renew_singleton_lease(
    namespace: str, holder: str, duration_s: int
) -> LeaseOutcome:
    """Refresh our hold on the Lease.

    ``lost`` means another live instance has taken the lease from us — the
    caller must terminate.  A transient API failure is ``error``: the caller
    keeps running and retries, since a renewal blip is not evidence of a
    duplicate.
    """
    now = datetime.now(timezone.utc)
    try:
        lease = await _run(
            _coordination_v1.read_namespaced_lease, LEASE_NAME, namespace
        )
        current = getattr(lease.spec, "holder_identity", None)
        if current is not None and current != holder:
            age = _lease_age_seconds(lease, now)
            expiry = getattr(lease.spec, "lease_duration_seconds", None) or duration_s
            if age is not None and age <= expiry:
                return LeaseOutcome(status="lost", holder=current, age_s=age)
        transitions = getattr(lease.spec, "lease_transitions", 0) or 0
        await _run(
            _coordination_v1.replace_namespaced_lease,
            LEASE_NAME,
            namespace,
            _lease_body(
                holder, duration_s, now, acquire=False, transitions=transitions,
                resource_version=_lease_resource_version(lease),
            ),
        )
        log.debug("%s", kv(event="k8s.lease_write", name=LEASE_NAME, mode="renewed"))
        return LeaseOutcome(status="acquired", holder=holder, mode="renewed")
    except Exception as exc:  # noqa: BLE001 — fail open, the caller keeps running
        return LeaseOutcome(status="error", err=str(exc))
